#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

#include "images/eggman_title.h"
#include "images/gamebg.h"
#include "images/eggman_player.h"
#include "images/emerald.h"
#include "images/win_screen_edited.h"
#include "images/lose_screen_edited.h"
#include "images/title_screen_edited.h"
#include "images/ss_title.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};
int collision(struct eggman p, struct collision_point x) {
    if (p.row < x.row + x.height && p.row + 10 > x.row &&
        p.col < x.col + x.width && p.col + 10 > x.col) {
        return 1;
    }
    return 0;
}

void getTime(void) {
    static int previousTime = -1;
    time.row = 2;
    time.col = 1;
    time.seconds = vBlankCounter / 60;
    if (time.seconds != previousTime) {
        char buffer[20];
        snprintf(buffer, sizeof(buffer), "%d s", time.seconds);
        drawRectDMA(0, 2, 30, 9, BLACK);
        drawString(time.row, time.col, buffer, WHITE);
        previousTime = time.seconds;
    }
}

int main(void) {

  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;
  int drawn = -1;
  int gameDrawn = -1;
  int loseDrawn = -1;
  int winDrawn = -1;
  struct collision_point time_bg = {
    .row = 0,
    .col = 2,
    .width = 30,
    .height = 9
  };

  //making vertical lasers
  struct vertical_laser v_lasers = {
    .v_stats = {
        {10, 30, 6, 20},
        {125, 65, 6, 20},
        {60, 15, 6, 20},
        {110, 25, 6, 20},
        {65, 40, 6, 20},
        {40, 110, 6, 20},
        {90, 150, 6, 20},
        {25, 65, 6, 20},
        {15, 130, 6, 20},
        {50, 200, 6, 20},
        {100, 200, 6, 20},
        {80, 220, 6, 20},
        {60, 66, 6, 20},
        {70, 120, 6, 20},
        {100, 90, 6, 20},
        {120, 130, 6, 20},
        {115, 180, 6, 20},
        {45, 150, 6, 20},
        {10, 170, 6, 20},
        {10, 215, 6, 20},
        {10, 90, 6, 20},
        {88, 50, 6, 20},
        {135, 40, 6, 20},
        {133, 198, 6, 20},
        {84, 170, 6, 20},
        {45, 224, 6, 20},
        {45, 87, 6, 20}
    }
  };
  //making horizontal lasers
  struct horizontal_laser h_lasers = {
    .h_stats = {
        {45, 10, 20, 6},
        {50, 45, 20, 6},
        {15, 50, 20, 6},
        {90, 5, 20, 6},
        {140, 10, 20, 6},
        {120, 40, 20, 6},
        {120, 105, 20 ,6},
        {140, 90, 20, 6},
        {75, 85, 20, 6},
        {102, 115, 20, 6},
        {140, 168, 20 ,6},
        {50, 120, 20 ,6},
        {123, 145, 20, 6},
        {70, 170, 20, 6},
        {85, 190, 20, 6},
        {50, 170, 20, 6},
        {35, 185, 20, 6},
        {92, 70, 20, 6},
        {149, 123, 20, 6},
        {115, 218, 20, 6},
        {12, 185, 20, 6},
        {4, 105, 20, 6}
      }
  };

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    waitForVBlank();
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
        if (drawn == -1) {
            waitForVBlank();
            drawFullScreenImageDMA(title_screen_edited); //set title screen fullscreen image
            drawImageDMA(5, 180, 30, 30, ss_title);
            ss_image.row = 5;
            ss_image.col = 180;
            drawn = 0;
        }
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
            drawn = -1;
            vBlankCounter = 0;
            state = PLAY;
        }
        static int direction = 1;
        waitForVBlank();
        int new_col = ss_image.col + direction;
        if (new_col + 30 >= 240 || new_col <= 110) {
            direction *= -1;
            new_col = ss_image.col + direction;
        }
        if (direction > 0) {
            //moving right
            undrawImageDMA(ss_image.row, ss_image.col, direction, 30, title_screen_edited);
        } else {
            //moving left
            undrawImageDMA(ss_image.row, ss_image.col + 30 + direction, -direction, 30, title_screen_edited);
        }
        ss_image.col = new_col;
        drawImageDMA(ss_image.row, ss_image.col, 30, 30, ss_title);

        break;
      case PLAY:
        getTime();
        if (gameDrawn == -1) {
            waitForVBlank();
            drawFullScreenImageDMA(game_background);

            //player
            drawImageDMA(12,15, 10, 10, eggman_player);
            player.row = 12;
            player.col = 15;
            player.speed = 3;

            //emerald
            drawImageDMA(130, 213, 15, 15, emerald);
            masterEmerald.row = 130;
            masterEmerald.col = 213;
            masterEmerald.width = 15;
            masterEmerald.height = 15;

            for (int i = 0; i < 28; i++) {
                drawRectDMA(v_lasers.v_stats[i].row, v_lasers.v_stats[i].col, v_lasers.v_stats[i].width, v_lasers.v_stats[i].height, RED);
            }
            for (int i = 0; i < 22; i++) {
                drawRectDMA(h_lasers.h_stats[i].row, h_lasers.h_stats[i].col, h_lasers.h_stats[i].width, h_lasers.h_stats[i].height, RED);
            }
            gameDrawn = 0;
        }
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            gameDrawn = -1;
            state = START;
        }

        waitForVBlank();

        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
            //waitForVBlank();
            if (player.col + player.speed + 10 <= 240) {
                undrawImageDMA(player.row, player.col, player.speed, 10, game_background);
                player.col += player.speed;
                drawImageDMA(player.row, player.col, 10, 10, eggman_player);
            }
        }
        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
            //waitForVBlank();
            if (player.col - player.speed >= 0) {
                undrawImageDMA(player.row, player.col + 10 - player.speed, player.speed, 10, game_background);
                player.col -= player.speed;
                drawImageDMA(player.row, player.col, 10, 10, eggman_player);
            }
        }
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
            //waitForVBlank();
            if (player.row - player.speed >= 0) {
                undrawImageDMA(player.row + 10 - player.speed, player.col, 10, player.speed, game_background);
                player.row -= player.speed;
                drawImageDMA(player.row, player.col, 10, 10, eggman_player);
            }
        }
        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
            //waitForVBlank();
            if (player.row + player.speed + 10 <= 160) {
                undrawImageDMA(player.row, player.col, 10, player.speed, game_background);
                player.row += player.speed;
                drawImageDMA(player.row, player.col, 10, 10, eggman_player);
            }
        }

        //check collisions for vertical lasers
        for (int i = 0; i < 28; i++) {
            if (collision(player, v_lasers.v_stats[i]) == 1) {
                gameDrawn = -1;
                state = LOSE;
            }
        }
        //check collisions for horizontal lasers
        for (int i = 0; i < 22; i++) {
            if (collision(player, h_lasers.h_stats[i]) == 1) {
                gameDrawn = -1;
                state = LOSE;
            }
        }
        //check if player collides with emerald
        if (collision(player, masterEmerald) == 1) {
            gameDrawn = -1;
            state = WIN;
        }

        if (collision(player, time_bg) == 1) {
            gameDrawn = -1;
        }

        break;
      case WIN:
        if (winDrawn == -1) {
            waitForVBlank();
            drawFullScreenImageDMA(win_screen_edited);
            winDrawn = 0;
        }
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            winDrawn = -1;
            state = START;
        }
        break;
      case LOSE:
        if (loseDrawn == -1) {
            waitForVBlank();
            drawFullScreenImageDMA(lose_screen_edited);
            loseDrawn = 0;
        }
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            loseDrawn = -1;
            state = START;
        }
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  return 0;
}
